### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ExoPlant** [ExoPlant/packwiz-gui#48]
List of things that need to be done
- [ ] `curseforge import`
- [ ] `serve`
- [ ] `curseforge detect`
- [ ] `curseforge export --side`
- [ ] `curseforge open`
- [ ] `liteloader` for init
- [ ] `utils` markdown files
- [ ] `latest version for loader/mc`

**Comment by Samisafool** [comment]
TOO

**Comment by ExoPlant** [comment]
Moved to github projects. https://github.com/ExoPlant/packwiz-gui/projects/1
